### ISSUE TITLE
[Bug]: Google OAuth Token is not being refreshed

### ISSUE THREAD

**Issue by renekahr** [lowcoder-org/lowcoder#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The refresh token is not revalidated. My users are constantly being logged out.

### Expected Behavior

Refresh the OAuth token.

### Steps to reproduce

Set up the Google OAuth and use it for a while.

**Comment by lanedsmu** [comment]
I wonder if this is the same problem we're seeing in [this report](https://discord.com/channels/1096896040159957084/1231984354176274514).  

Do you happen to get this error in the API logs when this occurs?
` ERROR o.l.a.f.exception.CustomErrorWebExceptionHandler#render:92    [nioEventLoopGroup-3-2]: oops class org.lowcoder.sdk.exception.BizException, Sorry, this log in channel is not supported.`

if so, we are experiencing the same thing.  The front-end shows this, which seems to me to suggest, as you mention, that the refresh token isn't being utilized:
`"GET /apps/66393ee3d6f8ff1093a724b9/view HTTP/1.1" 304 0 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
"GET /api/v1/users/me HTTP/1.1" 403 86 "https://lowcoder.url/apps/66393ee3d6f8ff1093a724b9/view" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
"GET /api/users/currentUser HTTP/1.1" 403 86 "https://lowcoder.url/apps/66393ee3d6f8ff1093a724b9/view" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
`

**Comment by branek** [comment]
Self-hosted All-In-One image, docker-compose. Same issue with non refreshed Google OAuth session observed.

Log from api-service:
```
2024-09-05 04:20:52.300 ERROR o.l.a.a.r.oauth2.request.AbstractOauth2Request#lambda$refresh$5:44    [reactor-http-epoll-5]: failed to refresh token:  
org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest: 400 Bad Request from POST https://www.googleapis.com/oauth2/v4/token
        at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:307)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoIgnoreThen] :
        reactor.core.publisher.Mono.then
        org.springframework.web.reactive.function.client.DefaultWebClient.releaseIfNotConsumed(DefaultWebClient.java:193)
Error has been observed at the following site(s):
        *___________Mono.then ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient.releaseIfNotConsumed(DefaultWebClient.java:193)
        |_                    ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.lambda$applyStatusHandlers$17(DefaultWebClient.java:687)
        *________Mono.flatMap ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.applyStatusHandlers(DefaultWebClient.java:687)
        |_ Mono.onErrorResume ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.applyStatusHandlers(DefaultWebClient.java:688)
        |_       Mono.flatMap ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.applyStatusHandlers(DefaultWebClient.java:693)
        |_         checkpoint ⇢ 400 BAD_REQUEST from POST https://www.googleapis.com/oauth2/v4/token [DefaultWebClient]
        |_ Mono.switchIfEmpty ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.handleBodyMono(DefaultWebClient.java:656)
        |_                    ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.lambda$bodyToMono$2(DefaultWebClient.java:573)
        *___________Mono.then ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient.releaseIfNotConsumed(DefaultWebClient.java:193)
        |_                    ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.lambda$applyStatusHandlers$18(DefaultWebClient.java:688)
        *________Mono.flatMap ⇢ at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultResponseSpec.bodyToMono(DefaultWebClient.java:572)
        |_       Mono.flatMap ⇢ at org.lowcoder.api.authentication.request.oauth2.request.GenericAuthRequest.refreshAuthToken(GenericAuthRequest.java:71)
        |_       Mono.flatMap ⇢ at org.lowcoder.api.authentication.request.oauth2.request.AbstractOauth2Request.refresh(AbstractOauth2Request.java:42)
Original Stack Trace:
                at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:307)
                at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:214)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
                at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
                at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
                at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
                at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)
                at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
                at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446)
                at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500)
                at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:793)
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
                at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
                at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by figwood** [comment]
This happens when the refresh token is null and the accessToken expired, and the pod will gracefully shutdown and restart,  also the refresh token will disappear and trigger this bug.

**Comment by goldants** [comment]
Just fixed and merged to dev.

**Comment by branek** [comment]
After almost one day of testing I am not able to 100% confirm that fix is ok.
With this fix in all-in-one image I still get logged out sometimes. Not sure why, and not able to catch any pattern. 
I'm not saying that fix is not ok, just I'm not clear why I got logged out. There is some entries in logs:

```
2024-09-10 13:48:22.711 ERROR o.l.a.f.filter.UserSessionPersistenceFilter#lambda$refreshOauthToken$5:133    [boundedElastic-226]: Refresh token is empty 
2024-09-10 13:48:22.711 ERROR o.l.a.f.filter.UserSessionPersistenceFilter#lambda$refreshOauthToken$5:141    [boundedElastic-226]: Failed to refresh access token. Removing user sessions/tokens. 
2024-09-10 13:48:23.810 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-228]: Hikari hashcode: 1649558281, active: 0, idle: 1, wait: 0, total: 1 
2024-09-10 13:48:23.932 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$10:162  POST /api/v1/query/execute [nioEventLoopGroup-3-2]: oops, Sorry, it appears you don't have the permission. 
2024-09-10 13:48:24.125 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$10:162  POST /api/v1/query/execute [nioEventLoopGroup-3-2]: oops, Sorry, it appears you don't have the permission. 
2024-09-10 13:48:24.132 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$10:162  POST /api/v1/query/execute [nioEventLoopGroup-3-2]: oops, Sorry, it appears you don't have the permission. 
2024-09-10 13:48:24.149 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$10:162  POST /api/v1/query/execute [nioEventLoopGroup-3-2]: oops, Sorry, it appears you don't have the permission. 
2024-09-10 13:48:24.157 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$10:162  POST /api/v1/query/execute [nioEventLoopGroup-3-2]: oops, Sorry, it appears you don't have the permission. 
2024-09-10 13:48:25.263 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-227]: Hikari hashcode: 1649558281, active: 0, idle: 1, wait: 0, total: 1 
2024-09-10 13:48:25.371 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-228]: Hikari hashcode: 355969434, active: 0, idle: 1, wait: 0, total: 1 
2024-09-10 13:48:28.812 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-227]: Hikari hashcode: 1649558281, active: 0, idle: 1, wait: 0, total: 1 
2024-09-10 13:48:29.168 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$10:162  GET /api/v1/applications/66d9c49d462f0673bb542106/view [boundedElastic-226]: oops, Unknown user, you have to log in first. 
```

Not sure why token is empty? Maybe inactivity?

**Comment by goldants** [comment]
There was a mistake in previous fix.
I just fixed the issue and tested and pushed.

**Comment by branek** [comment]
I'm sorry, but this is still not working. I again updated to the latest `dev` image: Version: 2.4.5-"dev #f55fb7f".

Restarted docker, logged in after everything was up and running and worked on without any pause or inactivity. After one hour, I got this timestamps clearly shows that after one hour, RefreshToken was empty:
```
2024-09-11 19:08:52.675 INFO i.m.r.c.e.operation.migrate.MigrateExecutorBase#executeMigration:71    [main]: Mongock has finished 
███████ ███████ ██████  ██    ██ ███████ ██████      ███████ ████████  █████  ██████  ████████ ███████ ██████
██      ██      ██   ██ ██    ██ ██      ██   ██     ██         ██    ██   ██ ██   ██    ██    ██      ██   ██
███████ █████   ██████  ██    ██ █████   ██████      ███████    ██    ███████ ██████     ██    █████   ██   ██
     ██ ██      ██   ██  ██  ██  ██      ██   ██          ██    ██    ██   ██ ██   ██    ██    ██      ██   ██
███████ ███████ ██   ██   ████   ███████ ██   ██     ███████    ██    ██   ██ ██   ██    ██    ███████ ██████

2024-09-11 19:08:52.678 INFO o.lowcoder.runner.eventlistener.AppEventListener#onApplicationEvent:25    [main]: check BizError duplicates: 98 
2024-09-11 19:09:14.967 INFO com.zaxxer.hikari.HikariDataSource#<init>:80    [plugin-executor-6]: HikariPool-1 - Starting... 
2024-09-11 19:09:14.976 INFO com.zaxxer.hikari.HikariDataSource#<init>:80    [plugin-executor-7]: HikariPool-2 - Starting... 
2024-09-11 19:09:15.262 INFO com.zaxxer.hikari.pool.HikariPool#checkFailFast:565    [plugin-executor-6]: HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@c91a9bc 
2024-09-11 19:09:15.265 INFO com.zaxxer.hikari.HikariDataSource#<init>:82    [plugin-executor-6]: HikariPool-1 - Start completed. 
2024-09-11 19:09:15.291 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-8]: Hikari hashcode: 665618769, active: 0, idle: 1, wait: 0, total: 1 
2024-09-11 19:09:15.314 INFO com.zaxxer.hikari.pool.HikariPool#checkFailFast:565    [plugin-executor-7]: HikariPool-2 - Added connection com.mysql.cj.jdbc.ConnectionImpl@4469904b 
2024-09-11 19:09:15.317 INFO com.zaxxer.hikari.HikariDataSource#<init>:82    [plugin-executor-7]: HikariPool-2 - Start completed. 
2024-09-11 19:09:15.324 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-6]: Hikari hashcode: 678861975, active: 0, idle: 1, wait: 0, total: 1 
2024-09-11 19:09:15.718 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-8]: Hikari hashcode: 665618769, active: 0, idle: 1, wait: 0, total: 1 
2024-09-11 19:09:16.698 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-6]: Hikari hashcode: 665618769, active: 0, idle: 1, wait: 0, total: 1 
startMonthEpoch is: 1722539378000
endMonthEpoch is: 1725131378000
2024-09-11 19:09:52.405 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:11:52.404 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:13:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:15:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:17:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:19:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:21:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:23:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:25:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:27:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:29:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:31:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:33:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:35:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:36:54.214 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-22]: Hikari hashcode: 678861975, active: 0, idle: 1, wait: 0, total: 1 
2024-09-11 19:36:54.242 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-23]: Hikari hashcode: 665618769, active: 0, idle: 1, wait: 0, total: 1 
2024-09-11 19:36:54.816 INFO org.lowcoder.plugin.sql.SqlBasedQueryExecutor#blockingExecuteQuery:86    [plugin-executor-23]: Hikari hashcode: 665618769, active: 0, idle: 1, wait: 0, total: 1 
2024-09-11 19:37:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:39:52.404 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:41:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:43:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:45:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:47:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:49:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:51:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:53:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:55:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:57:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 19:59:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 20:01:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 20:03:52.404 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 20:05:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 20:07:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
2024-09-11 20:09:29.082 ERROR o.l.a.f.filter.UserSessionPersistenceFilter#lambda$refreshOauthToken$5:133    [boundedElastic-33]: Refresh token is empty 
2024-09-11 20:09:29.083 ERROR o.l.a.f.filter.UserSessionPersistenceFilter#lambda$refreshOauthToken$5:141    [boundedElastic-33]: Failed to refresh access token. Removing user sessions/tokens. 
2024-09-11 20:09:29.082 ERROR o.l.a.f.filter.UserSessionPersistenceFilter#lambda$refreshOauthToken$5:133    [boundedElastic-32]: Refresh token is empty 
2024-09-11 20:09:29.083 ERROR o.l.a.f.filter.UserSessionPersistenceFilter#lambda$refreshOauthToken$5:141    [boundedElastic-32]: Failed to refresh access token. Removing user sessions/tokens. 
2024-09-11 20:09:52.403 INFO org.lowcoder.runner.task.IoHeartBeatTask#lambda$ping$0:31    [lettuce-epollEventLoop-9-1]: schedule ping executed, result: true 
```

Is there anything else I could do to help debugging?

**Comment by dragonpoo** [comment]
Fixed and merged to dev, please check!

**Comment by adnanqaops** [comment]
This has been Fixed ( V2.6.0 ). So, closing out this Ticket. 
Feel free to open this ticket if you face this issue again.
