### ISSUE TITLE
[Bug]: OAuth unable to bind email to user

### ISSUE THREAD

**Issue by placidic** [lowcoder-org/lowcoder#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a successful GENERIC OAuth Implementation for Lowcoder against Microsoft Entra ID. 

When a new user is created automatically upon first login of the user, the new lowcoder-user object is not populating the email property. Furthermore, if the logged in user clicks the Profile Icon and attempts to manually bind the email address to the current user, an "Oops, service is busy" error message appears and the binding fails.
![image](https://github.com/user-attachments/assets/67e3bfb2-3a36-4d38-a662-0e1ef1031bfa)

I can confirm that the GENERIC data contained in the user object contains the email address value - but the local user email is blank.
![image](https://github.com/user-attachments/assets/a91450ac-818e-4104-99b7-8775e20a1b06)

With the new Lowcoder login experience in v2.5.0, this is causing issues when the user is trying to log in using the standard user login path. The email is unable to be found in the local lowcoder database and stops the user from proceeding.

There is a workaround however to still use the old workspace specific login path - once you go there, you still only see the Email Input, but if you enter an email address and click "Continue" it then refreshes and renders the SSO Buttons configured for that workspace. An extra step to log in now with 2.5.0, but at least accessible.

### Expected Behavior

I would expect that upon first login of the new user, the email address returned from the OAuth provider would be automatically bound to the lowcoder user object.

### Steps to reproduce

1. Set up Generic OAuth Provider with MS Entra ID - using 'email' for email binding
2. Obtain an Invite link for a new user
3. Log in using the invite link via SSO for the new User
4. Log out and try to log back in using the email address returned from the SSO Binding

### Environment

Lowcoder 2.5.0 Self-Hosted

**Comment by FalkWolsky** [comment]
We have a question: Did you use the mapping in Step 3 and map by a JSON path the field eMail?

**Comment by placidic** [comment]
I do have it mapped:
![image](https://github.com/user-attachments/assets/3205a14d-dd2f-4c5b-883e-2fbf60df428b)

And if I look at my currentUser state, it shows the email under the GENERIC attributes:
![image](https://github.com/user-attachments/assets/0b88010f-df76-4e6e-ad56-03c3b51edc9d)


After inspecting my jwt token, i then realized that there was no 'email' property returned in my token!
My assumption is that the email is getting returned during the user introspection call after authorization.
Although i'm sending the scope for 'email' it just allows permissions to it, but does not return it in the initial token response.

Would it be possible to update the local email address based on the result of a user introspection call in the case that user introspection is enabled?

At least I think i know why its not working =)

**Comment by FalkWolsky** [comment]
Idea behind this "manual binding" is to give great flexibility for many possible providers and integrations.

**Comment by placidic** [comment]
I'll try out a few variations and confirm. What's odd is that the current name of the email returned from user introspection is 'email' based on what shows under the extras=>GENERIC section under the currentUser object, which is how I have it mapped in the source mapping. 

Thanks for the feedback and I'll let you know!

**Comment by FalkWolsky** [comment]
We also have to try again. If it not works as intended - then we will fix it.

**Comment by dragonpoo** [comment]
@placidic 
Instead of oid, 'sub' should be mapped to uid.

@FalkWolsky @ludomikula 
Btw, about email binding, there is no such api in our backend.
/api/auth/email/bind?email={}&authId=EMAIL

**Comment by placidic** [comment]
Thanks for the tip @dragonpoo, I initially I was unsure what property would be ideal to map to the user id but the subscription property does make more sense.

I pulled the latest dev image released about 12 hours ago in dockerhub, updated my SSO mapping to use sub (which would also force a new user to be created), hoping that the references merged commit would resolve my email binding issue.

As expected, the new user is created and added to the workspce, but unfortunately, the lowcoder user is not created with the email property populated, however the email correctly shows in the extended OIDC properties within the extras section as before.

I've also confirmed that within my user introspection response, the email address is returned with the same mapped property name 'email'

**Comment by placidic** [comment]
including a screenshot of my user introspection response, showing the 'email' property
![image](https://github.com/user-attachments/assets/677b51cc-d030-4d52-997b-53e1d8edc232)

**Comment by dragonpoo** [comment]
User's email is populated only when you signup using email address or bind email after oauth signup.

**Comment by placidic** [comment]
Updated to the latest 2.5.1 image:
If I attempt to bind the email address after oauth signup, I get the following error:
![image](https://github.com/user-attachments/assets/4d635157-6635-476d-8eb0-2774ec137669)

In the logs I see the following error has occurred
```
2024-12-05 16:39:53.369 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$9:175 POST /api/auth/email/bind [nioEventLoopGroup-3-1]:
org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
at org.springframework.web.reactive.DispatcherHandler.lambda$createNotFoundError$3(DispatcherHandler.java:159)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
...
```

If i look in my developer tools within lowcoder - I see the matching email entered within the oauth element for the user.
![image](https://github.com/user-attachments/assets/fc185ac8-7c27-407b-b110-e7af90dbe847)


Is the expectation that the user creates an account FIRST via email, and THEN login via oAuth and then bind the 2 accounts together? That doesn't seem like it would be the expectation as the other user properties are transferred to the new account upon creation, but not the email address (which is only available from the user introspection token as our jwt token does not include that information)

**Comment by adnanqaops** [comment]
This has been fixed, and released in V2.6.1. So, closing out this ticket.
