### ISSUE TITLE
[Bug]: k8s API server crash

### ISSUE THREAD

**Issue by linonetwo** [lowcoder-org/lowcoder#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some related errors in log:

```
2024-06-29 06:58:21.441 WARN i.m.c.instrument.binder.jvm.ExecutorServiceMetrics#bindTo:304    [main]: Failed to bind as io.netty.util.concurrent.DefaultEventExecutorGroup is unsupported.
2024-06-29 06:58:19.802 WARN o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker#postProcessAfterInitialization:437    [main]: Bean 'pluginConfiguration' of type [org.lowcoder.api.framework.configuration.PluginConfiguration$$SpringCGLIB$$0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [meterRegistryPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies. 
2024-06-29 06:58:19.925 WARN o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker#postProcessAfterInitialization:437    [main]: Bean 'pluginAuthorizationManager' of type [org.lowcoder.api.framework.plugin.security.PluginAuthorizationManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [meterRegistryPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies.  


2024-06-29 06:58:24.045 INFO i.m.r.c.e.operation.migrate.MigrateExecutorBase#executeMigration:71    [main]: Mongock has finished 
███████ ███████ ██████  ██    ██ ███████ ██████      ███████ ████████  █████  ██████  ████████ ███████ ██████
██      ██      ██   ██ ██    ██ ██      ██   ██     ██         ██    ██   ██ ██   ██    ██    ██      ██   ██
███████ █████   ██████  ██    ██ █████   ██████      ███████    ██    ███████ ██████     ██    █████   ██   ██
     ██ ██      ██   ██  ██  ██  ██      ██   ██          ██    ██    ██   ██ ██   ██    ██    ██      ██   ██
███████ ███████ ██   ██   ████   ███████ ██   ██     ███████    ██    ██   ██ ██   ██    ██    ███████ ██████
2024-06-29 06:58:24.047 INFO o.lowcoder.runner.eventlistener.AppEventListener#onApplicationEvent:25    [main]: check BizError duplicates: 98 
2024-06-29 06:58:24.223 INFO org.lowcoder.api.misc.JsLibraryController#lambda$static$3:85    [reactor-http-epoll-8]: reloaded recommended js library: {"name":"jmespath","latestVersion":"0.16.0","homepage":"https://github.com/jmespath/jmespath.js","description":"JMESPath implementation in javascript","downloadUrl":"https://unpkg.com/jmespath/jmespath.js"} 
2024-06-29 06:58:24.352 INFO org.lowcoder.api.misc.JsLibraryController#lambda$static$3:85    [reactor-http-epoll-6]: reloaded recommended js library: {"name":"jspdf","latestVersion":"2.5.1","homepage":"https://github.com/mrrio/jspdf","description":"PDF Document creation from JavaScript","downloadUrl":"https://unpkg.com/jspdf/dist/jspdf.umd.min.js"} 
2024-06-29 06:58:25.312 INFO org.lowcoder.api.misc.JsLibraryController#lambda$static$3:85    [reactor-http-epoll-2]: reloaded recommended js library: {"name":"jsonpath","latestVersion":"1.1.1","homepage":"https://github.com/dchester/jsonpath#readme","description":"Query JavaScript objects with JSONPath expressions. Robust / safe JSONPath engine for Node.js.","downloadUrl":"https://unpkg.com/jsonpath/jsonpath.js"} 
2024-06-29 06:58:25.466 INFO org.lowcoder.api.misc.JsLibraryController#lambda$static$3:85    [reactor-http-epoll-4]: reloaded recommended js library: {"name":"i18next","latestVersion":"23.11.5","homepage":"https://www.i18next.com","description":"i18next internationalization framework","downloadUrl":"https://unpkg.com/i18next/dist/umd/i18next.min.js"} 
2024-06-29 06:58:51.378 ERROR o.l.api.framework.exception.GlobalExceptionHandler#lambda$doLog$8:155  GET /actuator/health [parallel-1]:  
org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
 at org.springframework.web.reactive.DispatcherHandler.lambda$createNotFoundError$3(DispatcherHandler.java:159)
 at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
 at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
 at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
 at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
 at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:241)
 at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:357)
 at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
 at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerComplete(FluxConcatMapNoPrefetch.java:275)
```

### Expected Behavior

It should have started.

### Steps to reproduce

Use this value

```
redis:
  externalUrl: 1.1.1.1:6379
  enabled: false
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis-password
    existingSecretPasswordKey: password
mongodb:
  service:
    externalUrl: 1.1.1.1:27017
  enabled: false
  auth:
    existingSecret: mongodb-password
    usernames:
      - lowcoder
    databases:
      - lowcoder
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: xxx.site
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: tls-secret
     hosts:
       - xxx.site
  
```

/actuator/health  seems does not exist in latest version?

### Environment

k8s

lowcoder version 2.4.1

**Comment by adnanqaops** [comment]
Confirmed from Ludo. This issue has been fixed by : https://github.com/lowcoder-org/lowcoder/pull/1075 .
So, closing out this ticket.
